export const mockdate = [
  {
    id: 1810,
    name: '龍山文創基地',
    name_zh: null,
    open_status: 1,
    introduction:
      '體驗式學習行文創基地\r\n\r\n萬華本身具豐富內涵與文化，無論是文字、視覺、聲音、表演、工藝甚至氣味與食物等，在在散發獨特的風貌，龍山文創基地以「培養在地設計師、藝術家、創作者」為主軸，發展在地品牌，以導覽、藝文表演、互動工作坊等讓民眾參與及體驗，讓旅客於此體驗，發掘萬華的文化與文創能量。\r\n\r\n從B2認識艋舺美與善\r\n\r\n重新塑造目前龍山文創基地給人的既定形象，從文創品、飲食、街景與服務皆彰顯萬華在地美與善的形象與特色，並將過去常民生活展示於此，讓到萬華的旅客以此為出發點，進而認識艋舺。',
    open_time:
      '週二至週日 11:00 - 21:00　\r\n週一 休館日\r\n*遇國定假日或連續假日延後一日休館',
    zipcode: '108',
    distric: '萬華區',
    address:
      '108 臺北市萬華區西園路一段145號B2 龍山寺地下街B2(龍山寺捷運站1號出口)',
    tel: '+886-2-23021598',
    fax: '',
    email: 'monga.longshan.b2@gmail.com',
    months: '01,07,02,08,03,09,04,10,05,11,06,12',
    nlat: 25.03607,
    elong: 121.49989,
    official_site: 'https://longshan-b2.taipei/home/zh-tw',
    facebook: 'https://www.facebook.com/mongaB2/',
    ticket: '',
    remind: '',
    staytime: '',
    modified: '2024-08-25 05:01:54 +08:00',
    url: 'https://www.travel.taipei/zh-tw/attraction/details/1810',
    category: [
      {
        id: 15,
        name: '藝文館所',
      },
      {
        id: 24,
        name: '主題商街',
      },
    ],
    target: [],
    service: [],
    friendly: [],
    images: [
      {
        src: 'https://www.travel.taipei/image/176830',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/176831',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/176832',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/176833',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/176834',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/176835',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/176837',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/176838',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/176839',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/176840',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/176841',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/176842',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/176843',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/176844',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/176826',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/176827',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/176828',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/176829',
        subject: '',
        ext: '.jpg',
      },
    ],
    files: [],
    links: [],
  },
  {
    id: 1560,
    name: '寧夏觀光夜市',
    name_zh: null,
    open_status: 1,
    introduction:
      '以「千歲宴」打響國際名聲，且獲得眾多美食雜誌和網路爭相報導的寧夏觀光夜市，包含民生西路、南京西路與重慶北路中間的路段，以臺灣傳統小吃為主，其中以大同區圓環附近令人懷念的古早味，最讓老臺北人津津樂道。\r\n▲圖片來源：臺北市政府觀光傳播局\r\n\r\n夜市首先將人車分道，方便民眾吃飯與購物，貼心的服務，而隨著科技進步，許多攤販及店家也開始轉型，能夠使用悠遊卡及行動支付，遊客們帶著手機就能吃遍夜市美食。\r\n▲圖片來源：臺北市政府觀光傳播局\r\n\r\n知名的「千歲宴」由2010年開始舉辦，名稱由來是因寧夏夜市攤販大多都已超過50年，加起來超過千歲，故取名為千歲宴。如要一嚐寧夏夜市美食「千歲宴」可電話預約或至官網預訂，建議人數7-10人，利用辦桌合菜的方式，讓遊客可以輕鬆享用20道臺灣在地小吃。\r\n▲圖片來源：臺北市政府觀光傳播局\r\n\r\n寧夏夜市的小吃充滿濃濃的臺灣味，香噴噴的滷肉飯和雞肉飯、清甜鮮美的蚵仔煎和大腸蚵仔麵線、現炒入味的沙茶牛肉、滋補養顏的豬肝湯、來自府城的臺南碗粿、吳郭魚湯、蛋黃芋餅等等，都讓人忍不住食指大動。夜市另一邊的攤販，以新奇好玩的雜貨和玩具為主，販售的商品頗具流行感，價格不貴，在飽嚐美食之餘，不妨也來走走逛逛。',
    open_time: '每日18:00~24:00',
    zipcode: '103',
    distric: '大同區',
    address: '103 臺北市大同區寧夏路(位於南京西路與民生西路間)',
    tel: '+886-2-25505220',
    fax: '',
    email: '',
    months: '01,07,02,08,03,09,04,10,05,11,06,12',
    nlat: 25.056678157775092,
    elong: 121.51536047458649,
    official_site: '',
    facebook:
      'https://www.facebook.com/pages/category/Food-Stand/%E5%AF%A7%E5%A4%8F%E8%A7%80%E5%85%89%E5%A4%9C%E5%B8%82-170921516284146/',
    ticket: '',
    remind: '',
    staytime: '',
    modified: '2024-08-25 05:01:39 +08:00',
    url: 'https://www.travel.taipei/zh-tw/attraction/details/1560',
    category: [
      {
        id: 23,
        name: '夜市商圈',
      },
    ],
    target: [],
    service: [
      {
        id: 144,
        name: '餐飲',
      },
      {
        id: 145,
        name: '購物',
      },
    ],
    friendly: [],
    images: [
      {
        src: 'https://www.travel.taipei/image/221821',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/221822',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/221813',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/221814',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/221815',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/221816',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/221817',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/221818',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/221819',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/221820',
        subject: '',
        ext: '.jpg',
      },
    ],
    files: [],
    links: [],
  },
  {
    id: 394,
    name: '三創生活',
    name_zh: null,
    open_status: 1,
    introduction:
      '「三創生活」坐落於市民大道三段與金山北路交界，佔地2,687坪，建築外觀呈現前瞻氣勢，立面設計詮釋產業特性，結合鄰近綠帶的視野，實踐自然與科技共生的設計理念。\r\n\r\n空間規劃導入科技生活、潮流影音、子親娛樂、動漫文化、探索體驗、創作育成及藝術展演等多元概念，結合園區內隨處可見的數位視屏，讓影像的多元樣貌，觸動對生活的無限想像。\r\n\r\n園區以人為核心，打造實踐未來的生活平台。期待能藉由互動、分享、探索、學習與創作，帶領大眾重新建構科技、文化與生活的連結。\r\n\r\n園區共12層樓，緊鄰光華數位新天地，提供選購3C產品的更多選擇。\r\n\r\n\r\n\r\n',
    open_time: '週日至週四 11:00-21:30／週五至週六及國定假日前夕 11:00-22:00',
    zipcode: '100',
    distric: '中正區',
    address: '100 臺北市中正區市民大道三段2號',
    tel: '+886-809-093300',
    fax: '',
    email: '',
    months: '01,07,02,08,03,09,04,10,05,11,06,12',
    nlat: 25.04535,
    elong: 121.53111,
    official_site: 'https://www.syntrend.com.tw/',
    facebook: 'https://www.facebook.com/syntrend/',
    ticket: '',
    remind: '',
    staytime: '',
    modified: '2024-08-25 05:01:27 +08:00',
    url: 'https://www.travel.taipei/zh-tw/attraction/details/394',
    category: [
      {
        id: 19,
        name: '親子共遊',
      },
      {
        id: 24,
        name: '主題商街',
      },
    ],
    target: [],
    service: [
      {
        id: 144,
        name: '餐飲',
      },
      {
        id: 145,
        name: '購物',
      },
      {
        id: 146,
        name: '公廁',
      },
      {
        id: 147,
        name: '停車場',
      },
      {
        id: 148,
        name: '失物招領',
      },
      {
        id: 149,
        name: '廣播服務',
      },
      {
        id: 150,
        name: '寄物櫃',
      },
    ],
    friendly: [],
    images: [
      {
        src: 'https://www.travel.taipei/image/65876',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/65877',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/65879',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/65880',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/65883',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/65884',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/65885',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/65886',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/65891',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/65874',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/65875',
        subject: '',
        ext: '.jpg',
      },
    ],
    files: [],
    links: [],
  },
  {
    id: 2365,
    name: '彩虹起跑線',
    name_zh: null,
    open_status: 1,
    introduction:
      '2020年9月，臺北市第二道炫目的彩虹地景「彩虹起跑線」在臺北市東區誕生了！位於臺北市政府前市民廣場。\r\n\r\n此處彩虹地景由市府延伸至議會方向，類似跑道的形式上巧妙劃了一條線，就像是奔往幸福的起點般，不僅再次傳達臺北市提倡性平的初心，更呼應每年在市府前起走的臺灣同志大遊行。彩虹地景彷彿凝聚著所有人的期待與熱情，讓大家在市府前踩著堅定的步伐，穩穩地朝著幸福之路前進。\r\n\r\n(資料來源：臺北市政府觀光傳播局)',
    open_time: '開放空間',
    zipcode: '110',
    distric: '信義區',
    address: '110 臺北市信義區市府路1號 (臺北市政府前市民廣場)',
    tel: '+886-2-27208889',
    fax: '',
    email: '',
    months: '01,07,02,08,03,09,04,10,05,11,06,12',
    nlat: 25.037697167430807,
    elong: 121.56339370393275,
    official_site: '',
    facebook: '',
    ticket: '',
    remind: '',
    staytime: '',
    modified: '2024-08-23 17:26:49 +08:00',
    url: 'https://www.travel.taipei/zh-tw/attraction/details/2365',
    category: [
      {
        id: 18,
        name: '公共藝術',
      },
    ],
    target: [
      {
        id: 61,
        name: '親子共學',
      },
      {
        id: 62,
        name: '校外教學',
      },
    ],
    service: [],
    friendly: [],
    images: [
      {
        src: 'https://www.travel.taipei/image/191906',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/191907',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/191908',
        subject: '',
        ext: '.jpg',
      },
    ],
    files: [],
    links: [],
  },
  {
    id: 2375,
    name: '松錦公園',
    name_zh: null,
    open_status: 1,
    introduction:
      '松錦公園分為松錦一號公園與松錦二號公園，同樣位於民生東路二段與吉林路交界，且鄰近捷運行天宮站，坐落於住宅區內，提供當地居民一個散步休憩的場所。公園內的植栽造景維持得乾淨整潔，園區內的涼亭舒適寬廣成為民眾交流談天的社交空間，此外松錦公園鄰近松江市場，可以順道至松江市場買些生鮮、日用品及走走逛逛。',
    open_time: '',
    zipcode: '104',
    distric: '中山區',
    address: '104 臺北市中山區民生東路二段127巷',
    tel: '+886-2-25850192',
    fax: '',
    email: '',
    months: '01,07,02,08,03,09,04,10,05,11,06,12',
    nlat: 25.05962,
    elong: 121.53211,
    official_site: '',
    facebook: '',
    ticket: '',
    remind: '',
    staytime: '',
    modified: '2024-08-22 16:45:08 +08:00',
    url: 'https://www.travel.taipei/zh-tw/attraction/details/2375',
    category: [
      {
        id: 19,
        name: '親子共遊',
      },
    ],
    target: [],
    service: [],
    friendly: [],
    images: [
      {
        src: 'https://www.travel.taipei/image/192862',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/192863',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/192864',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/192865',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/192866',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/192867',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/192868',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/192860',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/192861',
        subject: '',
        ext: '.jpg',
      },
    ],
    files: [],
    links: [],
  },
  {
    id: 2576,
    name: '國立臺灣博物館_鐵道部園區',
    name_zh: null,
    open_status: 1,
    introduction:
      '國定古蹟臺灣總督府鐵道部位於忠孝西路、塔城街、鄭州路、延平北路間，屬國營臺灣鐵路股份有限公司管轄。1885年臺灣巡撫劉銘傳聘請英國與德國顧問，於淡水河碼頭內建造機器局，組裝槍砲彈藥及鑄造貨幣，內有鎔鐵所、鍛工場等。1895年日本軍方接收機器局，改為臺北兵器修理所，製造並修理陸軍所管兵器，可製造彈丸、信管、小銃丸及藥筴、船舶、鐵道鐵橋等，之後改稱為臺灣砲兵工廠，1900年由陸軍省移交鐵道部，同年改為臺北工場。1908年臺灣西部縱貫鐵路開通，鐵路交通運量與車輛維修需求大增，1909年臺北工場向東擴張，新建車輛修理工場、塗工場。1915年起拆除基地南邊原有建物，1918年新建鐵道部廳舍，與臺北工場並存，成為南廳舍、北工廠配置，直到1934年臺北工場搬遷至松山(今國定古蹟臺北機廠)為止，街廓內原有將近四十棟建物，歷經2005年興建捷運以及2013古蹟修復拆除不保存者，目前尚餘十棟，其中包含八處法定文化資產：鐵道部、食堂、八角樓男廁、電源室、工務室、戰時指揮中心、清代機器局遺構以及臺北工場(不在鐵道部園區範圍內)。\r\n\r\n戰後鐵道部改為臺灣鐵路管理局。因都市計畫劃道路塔城街於1967年開通，切斷與西側鐵道部官舍群連結形成今日所見的街廓。1992年臺北市政府指定鐵道部廳舍為三級古蹟，1993年臺鐵總局遷移至臺北車站新廈。2005年文建會委託東海大學、中原大學進行古蹟調查研究及再利用規劃，2006年交通部與臺灣鐵路管理局，以及文建會與國立臺灣博物館簽訂臺灣博物館系統聯盟協議書，鐵道部古蹟修復再利用工作正式開始，以「鐵道部博物館園區」為基礎概念，目標為建置現代性展示主題之複合使用園區，並整合周邊都市及歷史涵構。2007年文建會指定為國定古蹟，並納入八角樓、食堂、電源室、工務室、戰時指揮中心為古蹟範圍，臺北工場及清代機器局遺址則分別由臺北市於2008年及2010年指定為市定古蹟，2009年起由臺博館代管此區土地建物。規劃中的鐵道博物館展示主題將主要架構在古蹟與基地、鐵道文化及現代性等相關議題之上，未來也將涉及整合西側原機器局工廠範圍內E1E2街廓。\r\n\r\n(資料來源：國立臺灣博物館)',
    open_time: '',
    zipcode: '103',
    distric: '大同區',
    address: '103 臺北市大同區延平北路一段2號',
    tel: '+886-2-25589790',
    fax: '',
    email: '',
    months: '01,07,02,08,03,09,04,10,05,11,06,12',
    nlat: 25.048833955296377,
    elong: 121.51138342916965,
    official_site: 'https://www.ntm.gov.tw/submenu_373.html',
    facebook: 'https://www.facebook.com/NTMuseum',
    ticket: '',
    remind:
      '1.定時導覽服務：週二至週日 10:30、14:30\r\n鐵道部園區導覽主題：認識鐵道部\r\n2.預約團體導覽服務時段：週二至週五，每場40～60分鐘 （國定假日及連假恕不開放團體預約導覽）\r\n請於導覽14天前至鐵道部團體預約導覽服務網站申請',
    staytime: '',
    modified: '2024-08-22 16:38:17 +08:00',
    url: 'https://www.travel.taipei/zh-tw/attraction/details/2576',
    category: [
      {
        id: 13,
        name: '歷史建築',
      },
      {
        id: 15,
        name: '藝文館所',
      },
      {
        id: 19,
        name: '親子共遊',
      },
    ],
    target: [
      {
        id: 61,
        name: '親子共學',
      },
      {
        id: 62,
        name: '校外教學',
      },
    ],
    service: [],
    friendly: [],
    images: [
      {
        src: 'https://www.travel.taipei/image/207889',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/207890',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/207891',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/207892',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/207893',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/207894',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/207895',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/207896',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/207888',
        subject: '',
        ext: '.jpg',
      },
    ],
    files: [],
    links: [
      {
        src: 'https://www.ntm.gov.tw/content_374.html',
        subject: '開放時間與票價',
      },
    ],
  },
  {
    id: 2636,
    name: '静心苑_松山療養所所長宿舍',
    name_zh: null,
    open_status: 1,
    introduction:
      '松山療養所成立於1915年，是臺灣最早的肺結核病收容機構，因著松山療養所的成立，誕生了所長宿舍，松山療養所所長宿舍應是在 1922 年〈總督府官舍標準化〉法令發布後所建置，當時高等官官舍之設置是具有一定特有之規範。\r\n\r\n靜心苑(松山療養所所長宿舍)為日式木構造建築，無論是雨淋板的設置、和式小屋二重樑屋架、空間格局、建材等，大多為日治時期營建技術之展現，其中室內傘型天花以及入口外玄關兩側柱型之裝飾皆為其特殊語彙之呈現，具有其文化資產價值。\r\n\r\n資料來源：靜心苑官網、臉書',
    open_time:
      '營業時間：上午11:00開館 至 晚上21:00閉館。(營業時間內，免費開放參觀)\r\n休館日：每周一暨每年除夕農曆新年休館。\r\n暫停營業：天然災害依臺北市政府公告配合暫停營業。',
    zipcode: '115',
    distric: '南港區',
    address: '115 臺北市南港區昆陽街164號',
    tel: '+886-2-26530033',
    fax: '',
    email: '',
    months: '01,07,02,08,03,09,04,10,05,11,06,12',
    nlat: 25.048445771783808,
    elong: 121.59352272748947,
    official_site: 'https://jinghsinyuan.com.tw/',
    facebook: 'https://www.facebook.com/JingHsinYuan/',
    ticket: '',
    remind: '',
    staytime: '',
    modified: '2024-08-22 16:33:53 +08:00',
    url: 'https://www.travel.taipei/zh-tw/attraction/details/2636',
    category: [
      {
        id: 13,
        name: '歷史建築',
      },
      {
        id: 15,
        name: '藝文館所',
      },
    ],
    target: [],
    service: [
      {
        id: 143,
        name: '場地租用',
      },
      {
        id: 144,
        name: '餐飲',
      },
      {
        id: 145,
        name: '購物',
      },
    ],
    friendly: [],
    images: [
      {
        src: 'https://www.travel.taipei/image/210627',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/210619',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/210620',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/210621',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/210622',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/210623',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/210624',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/210625',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/210626',
        subject: '',
        ext: '.jpg',
      },
    ],
    files: [],
    links: [],
  },
  {
    id: 23,
    name: '國立中正紀念堂',
    name_zh: null,
    open_status: 1,
    introduction:
      '中正紀念堂是為了紀念中華民國第一任總統蔣介石，他於1975年逝世，次年行政院就破土開建中正紀念堂，設計師是設計圓山大飯店的楊卓成。\r\n\r\n紀念堂原址是陸軍總部，當時是臺北市區內最大的軍區，據說從大陸運過來的黃金，就曾經存放在這個地方。紀念堂採用的藍白兩色，是國旗上面主要的顏色，紀念堂頂部天穹的裝飾是青天白日12道光芒，銅像朝西面對總統府和中國大陸，其中都有特殊的意義。隨著民主演進思想開放，紀念堂前的廣場已成了民主運動的集會場。\r\n\r\n位於中正紀念堂左右兩側的國家音樂廳與國家戲劇院。戲劇院為戲劇、舞蹈等表演活動的場地，經常舉辦大型的表演活動，包括京劇、戲劇、兒童節目等；音樂廳是臺灣最具水準的音樂展演空間，經常舉辦室內樂，交響樂等大型的音樂活動。而兩廳院前廣場也會不定時舉辦戲劇、音樂活動，吸引眾多遊客前往欣賞。\r\n\r\n白牆藍瓦，70公尺高聳立在紀念公園的中央，不論從哪個角度看過去，都很宏偉。國外觀光客來到臺灣，不論行程如何排，都一定會到這裡來參觀一下。紀念堂的下方有陳列和展覽，也有紀念品販售。\r\n',
    open_time:
      '紀念堂開放時間：am09:00-pm06:00（星期一不休館）\r\n紀念公園開放時間：am05:00-pm12:00\r\n(休館日：除年度機電保養日、二二八紀念日、春節除夕及大年初一休館外，幾乎全年不休館)',
    zipcode: '100',
    distric: '中正區',
    address: '100 臺北市中正區中山南路21號',
    tel: '+886-2-23431100',
    fax: '',
    email: '',
    months: '01,07,02,08,03,09,04,10,05,11,06,12',
    nlat: 25.03619,
    elong: 121.51868,
    official_site: 'http://www.cksmh.gov.tw/',
    facebook: 'https://www.facebook.com/cksmhfb/?locale=zh_TW',
    ticket: '',
    remind:
      '升降旗時間：\r\n夏令時間：4/1~9/30\r\n*升旗：6:00AM    降旗：6:10 PM\r\n冬令時間：10/1~3/31\r\n*升旗：6:30AM    降旗：5:10 PM\r\n \r\n※國軍儀隊禮兵巡查及訓練展示（自113年7月15日實施)：\r\n1.每日上午9點至下午5點，每逢整點實施1次，每天9次(每次約15分鐘)：\r\n上午：9:00、10:00、11:00、12:00\r\n下午：1:00、2:00、3:00、4:00、5:00\r\n2.訓練展示地點：主堂體戶外正面階梯下方之民主大道。\r\n3.如遇雨天則不實施。',
    staytime: '',
    modified: '2024-08-22 16:30:56 +08:00',
    url: 'https://www.travel.taipei/zh-tw/attraction/details/23',
    category: [
      {
        id: 13,
        name: '歷史建築',
      },
      {
        id: 15,
        name: '藝文館所',
      },
      {
        id: 25,
        name: '無障礙旅遊推薦景點',
      },
    ],
    target: [
      {
        id: 61,
        name: '親子共學',
      },
      {
        id: 62,
        name: '校外教學',
      },
      {
        id: 65,
        name: '賞鳥族',
      },
    ],
    service: [
      {
        id: 141,
        name: '無障礙設施',
      },
      {
        id: 143,
        name: '場地租用',
      },
      {
        id: 144,
        name: '餐飲',
      },
      {
        id: 145,
        name: '購物',
      },
      {
        id: 146,
        name: '公廁',
      },
      {
        id: 147,
        name: '停車場',
      },
      {
        id: 148,
        name: '失物招領',
      },
      {
        id: 149,
        name: '廣播服務',
      },
      {
        id: 150,
        name: '寄物櫃',
      },
    ],
    friendly: [],
    images: [
      {
        src: 'https://www.travel.taipei/image/222951',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/222952',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/222953',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/222954',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/222955',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/222956',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/222957',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/222958',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/222959',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/222960',
        subject: '',
        ext: '.jpg',
      },
    ],
    files: [],
    links: [],
  },
  {
    id: 22,
    name: '國立臺灣博物館',
    name_zh: null,
    open_status: 1,
    introduction:
      '這是臺灣歷史最悠久的博物館，1899年設立了此館前身「臺灣總督府民政部殖產局商品陳列館」，1908年，正式設立「臺灣總督府博物館」於今總統府後方的舊彩票局。清代舊天后宮原址被拆除，其地建造「兒玉總督後藤民政長官紀念館」，1945年改名為「臺灣省博物館」，1949年更名為「臺灣省立博物館」，1999年定名為「國立臺灣博物館」。\r\n\r\n這位於臺北火車站前的博物館，外觀為希臘式建築，有巨大柱子和花葉紋飾的牆、羅馬圓頂，大廳四周有32根柱子，柱頭上有精緻的裝飾，圓頂下是一面彩繪玻璃天窗，陽光穿過玻璃，在地面映出美麗的光彩。它歷經臺灣的滄桑歷史，仍有著當年創館的規模。除了各期展覽，館內舉辦各種活動，歡迎學生、教師、親子、社會人士來參加。\r\n\r\n',
    open_time:
      '週二至週日每日上午9:30起至下午5:00止\r\n＊每週一、除夕及春節初一休館。\r\n＊逢國定假日及連續假期均照常開館',
    zipcode: '100',
    distric: '中正區',
    address: '100 臺北市中正區襄陽路2號',
    tel: '+886-2-23822566',
    fax: '',
    email: '',
    months: '01,07,02,08,03,09,04,10,05,11,06,12',
    nlat: 25.04276,
    elong: 121.51503,
    official_site: 'https://www.ntm.gov.tw/',
    facebook: 'https://www.facebook.com/NTMuseum',
    ticket:
      '臺博館本館及古生物館一次購票(當日)可參觀兩館\r\n全票：每張 30元｜半票：每張 15元\r\n四館聯票 全票：130元 ｜半票：65元\r\n會員卡 全票：300元\r\n＊半票優待：學生、6至12歲兒童，年滿65歲以上的民眾假日半票，機關學校團體二十人(含)以上(須一週前網路預約申請)\r\n＊免票優待，均憑證(函)優待，未滿六歲之學齡前兒童，年滿六十五歲以上的民眾平日免費．身心障礙者及其陪同者一人，持中華民國博物館學會、ICOM、AAM會員卡(證)，持志願服務榮譽卡\r\n＊臺博館提供各館悠遊卡、信用卡、台灣Pay售票服務\r\n＊於閉館前30分鐘停止售票服務',
    remind:
      '請勿於館內吸煙、飲食、奔跑嬉戲及其他有安全疑慮之行為。\r\n請勿攜帶食物、液體、傘具、危險物或易燃物入館。\r\n請依規定購票，接洽公務者請至館前行政大樓。\r\n服裝不整、攜帶寵物者(導盲犬除外)謝絕入館。\r\n請勿使用閃光燈、腳架及自拍棒攝影，並禁止做任何未經許可之商業及出版使用。\r\n本館大門口備有身心障礙專用電梯。\r\n華語定時導覽AM10:30、PM2:30。\r\n提供寄物收納櫃：大置物櫃40*40*80cm、小置物櫃40*40*40cm',
    staytime: '',
    modified: '2024-08-22 16:24:33 +08:00',
    url: 'https://www.travel.taipei/zh-tw/attraction/details/22',
    category: [
      {
        id: 13,
        name: '歷史建築',
      },
      {
        id: 15,
        name: '藝文館所',
      },
      {
        id: 18,
        name: '公共藝術',
      },
      {
        id: 25,
        name: '無障礙旅遊推薦景點',
      },
    ],
    target: [
      {
        id: 61,
        name: '親子共學',
      },
      {
        id: 62,
        name: '校外教學',
      },
    ],
    service: [
      {
        id: 141,
        name: '無障礙設施',
      },
      {
        id: 143,
        name: '場地租用',
      },
      {
        id: 146,
        name: '公廁',
      },
      {
        id: 149,
        name: '廣播服務',
      },
      {
        id: 150,
        name: '寄物櫃',
      },
    ],
    friendly: [
      {
        id: 387,
        name: '英語友善',
      },
      {
        id: 388,
        name: '日語友善',
      },
      {
        id: 390,
        name: '行動裝置充電',
      },
      {
        id: 392,
        name: '無障礙友善服務',
      },
      {
        id: 394,
        name: '信用卡/悠遊卡/第三方支付服務',
      },
      {
        id: 397,
        name: '販售公平貿易商品',
      },
      {
        id: 398,
        name: 'WiFi友善',
      },
      {
        id: 400,
        name: '哺(集)乳友善',
      },
    ],
    images: [
      {
        src: 'https://www.travel.taipei/image/63528',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/63508',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/63510',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/63516',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/63520',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/63521',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/63523',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/63527',
        subject: '',
        ext: '.jpg',
      },
    ],
    files: [],
    links: [],
  },
  {
    id: 21,
    name: '國立臺灣科學教育館',
    name_zh: null,
    open_status: 1,
    introduction:
      '臺灣科學教育館，為科學教育而設，適合所有大人小孩來參觀。地下室為兒童益智探索館，還有一個地底世界展，3, 4樓有生命科學、自然科學展，5, 6樓有物質科學、數學與地球科學展，7, 8樓為特展，可以看到世界性的科學展覽。館內設有各種體驗裝置，可與展品互動。\r\n\r\n在這也可看電影，3D動感電影院是一個動感模擬影院，雙人式液壓動感座椅，與影像同步動作，有如坐在雲宵飛車或飛行座艙上，身歷其境。立體虛擬實境劇場，採用高解析立體影像效果，讓觀看影片更有臨場感。這是個寓教於樂的優良場所，歡迎大家來玩。\r\n\r\n',
    open_time:
      '週六、週日、國定假日、寒暑假：\r\n9:00~18:00 | 17:00截止入場 | 售票時間：9:00~17:00\r\n\r\n非寒暑假之週二至週五：\r\n9:00~17:00 | 16:00截止入場 | 售票時間：9:00~16:00 \r\n\r\n9F圖書館開放時間調整如下：\r\n週六、週日、國定例假日、寒暑假：9:00~18:00\r\n非寒暑假之週二至週五：9:00~17:00\r\n備註：每週一休館(國定假日及特定假日除外、寒暑假天天開館) ',
    zipcode: '111',
    distric: '士林區',
    address: '111 臺北市士林區士商路189號',
    tel: '+886-2-66101234',
    fax: '',
    email: '',
    months: '01,07,02,08,03,09,04,10,05,11,06,12',
    nlat: 25.09613,
    elong: 121.51669,
    official_site: 'https://www.ntsec.gov.tw/',
    facebook: '',
    ticket: '請參考官方網站票價資訊。',
    remind: '',
    staytime: '',
    modified: '2024-08-22 16:18:44 +08:00',
    url: 'https://www.travel.taipei/zh-tw/attraction/details/21',
    category: [
      {
        id: 15,
        name: '藝文館所',
      },
      {
        id: 18,
        name: '公共藝術',
      },
      {
        id: 19,
        name: '親子共遊',
      },
      {
        id: 25,
        name: '無障礙旅遊推薦景點',
      },
    ],
    target: [
      {
        id: 61,
        name: '親子共學',
      },
      {
        id: 62,
        name: '校外教學',
      },
    ],
    service: [
      {
        id: 141,
        name: '無障礙設施',
      },
      {
        id: 146,
        name: '公廁',
      },
      {
        id: 149,
        name: '廣播服務',
      },
    ],
    friendly: [],
    images: [
      {
        src: 'https://www.travel.taipei/image/63485',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/63486',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/63489',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/63492',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/63496',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/63497',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/63498',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/63501',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/63484',
        subject: '',
        ext: '.jpg',
      },
    ],
    files: [],
    links: [
      {
        src: 'https://www.ntsec.gov.tw/User/Article.aspx?a=85',
        subject: '門票資訊',
      },
      {
        src: 'https://www.ntsec.gov.tw/article/detail.aspx?a=80',
        subject: '開放時間',
      },
    ],
  },
  {
    id: 2639,
    name: '五分吊橋遺址',
    name_zh: null,
    open_status: 1,
    introduction:
      '為臺北市區基隆河少數現存之吊橋遺址。吊橋之設立係作為早期內湖地區運送煤礦之交通要道，其遺址乃地方產業發展之歷史見證。\r\n\r\n該吊橋為內湖區跨越基隆河最早的一座煤炭運輸專用吊橋，吊橋橋面已於民國60、70年間拆除，目前只殘留北河岸的橋柱。\r\n\r\n(文字來源：國家文化資產網)',
    open_time: '開放空間',
    zipcode: '114',
    distric: '內湖區',
    address: '114 臺北市內湖區安康路402號旁涵洞另一側',
    tel: '+886-2-27208889',
    fax: '',
    email: '',
    months: '01,07,02,08,03,09,04,10,05,11,06,12',
    nlat: 25.06518,
    elong: 121.61389,
    official_site:
      'https://nchdb.boch.gov.tw/assets/advanceSearch/historicalBuilding/20040715000002',
    facebook: '',
    ticket: '',
    remind: '',
    staytime: '',
    modified: '2024-08-22 16:17:01 +08:00',
    url: 'https://www.travel.taipei/zh-tw/attraction/details/2639',
    category: [
      {
        id: 13,
        name: '歷史建築',
      },
    ],
    target: [],
    service: [],
    friendly: [],
    images: [
      {
        src: 'https://www.travel.taipei/image/215394',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/215395',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/215396',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/215392',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/215393',
        subject: '',
        ext: '.jpg',
      },
    ],
    files: [],
    links: [],
  },
  {
    id: 19,
    name: '國立故宮博物院',
    name_zh: null,
    open_status: 1,
    introduction:
      '國立故宮博物院於1965年在外雙溪落成，中國宮殿式的建築，一至三樓為展覽陳列空間，四樓為休憩茶座「三希堂」。藏有全世界最多的中華藝術寶藏，收藏品主要承襲自宋、元、明、清四朝，幾乎涵蓋了整部五千年的中國歷史，數量近70萬件，使國立故宮博物院擁有「中華文化寶庫」的美名。\r\n\r\n故宮博物院內有兩種故宮三寶，一為藝術學界內的故宮三寶，三幅北宋巨碑式水墨畫，但因許多年才展出一次，鮮少人能親眼見到，便又分支出民間版的故宮三寶，也就是翠玉白菜、肉形石、毛公鼎。此三寶因像華人民間小吃「酸菜白肉鍋」，故被封為此稱號。\r\n\r\n國立故宮博物院院區左右側各有一座園林，左側為至善園，右側為至德園。至善園為仿宋代建築而建的庭園，除每周一休園，其餘時間皆可入園參觀，園內有兩座池、三處涼亭，還有許多魚及小動物，非常適合一家大小前來賞園。至德園位於至善路與故宮路交叉口，目前為免費參觀。園區面積不大，入口處是一個別緻的古典圓拱門，園內有一座蓮荷池，夏日來此可以看到大量的蓮花盛開。\r\n\r\n不想假日人擠人參觀故宮的話，故宮還提供了線上故宮的部分，可以透過展覽搶先看觀賞各展覽介紹；利用典藏賞析欣賞各個藏品的美麗樣貌；奇幻互動還能讓你有如進入書畫中，一起感受古人的作品；如果還不夠，可以一同走進故宮，利用720&deg; VR讓你彷彿置身於故宮裡，在虛擬實境空間探索各區域，並能隨時隨地觀看或聆聽展覽及藏品介紹，讓你在家猶如身在故宮。\r\n\r\n國立故宮博物院除了展覽品豐富以外，提供專業導覽，並定期舉辦各類文物研習課程、專題演講及巡迴展出活動，出版百種以上的刊物及專輯，實為世界的文化寶地，國立故宮博物院是來臺灣旅遊的必訪之地。\r\n\r\n(部分資料來源：國立故宮博物院)',
    open_time:
      '國立故宮博物院北部院區自109年7月1日起延續開放時間調整措施：開放時間為每週二至週日09:00～17:00，每週一休館，取消每日及週末延長開館時間，同時暫停張大千紀念館對外開放。圖書文獻館自2020年10月19日(一)起至2021年1月底暫停對外開放。\r\n\r\n各項措施調整時間，將參考中央流行疫情指揮中心相關指示辦理，請隨時關注國立故宮博物院官網最新消息。造成您的不便，尚請見諒，感謝您的配合！',
    zipcode: '111',
    distric: '士林區',
    address: '111 臺北市士林區至善路二段221號',
    tel: '+886-2-28812021',
    fax: '',
    email: 'service@npm.gov.tw',
    months: '01,07,02,08,03,09,04,10,05,11,06,12',
    nlat: 25.10236,
    elong: 121.54849,
    official_site: 'https://www.npm.gov.tw/',
    facebook: 'https://www.facebook.com/npmgov/',
    ticket: '門票及各展區開放時間依官方網站公告為主。',
    remind:
      '※本景點為【士林北藝-無圍牆博物館】景點範圍\r\n＊每周一休館\r\n如有需要星期一可配合專場開放\r\n聯繫方式：賴先生\r\n02-28812021#2159\r\n＊免費參觀時間：1月1日元旦、元宵節、5月18日國際博物館日、9月27日世界觀光日、10月10日國慶日。\r\n\r\n＊配合連續假日，112年度週一開館日1/2、1/23、2/27、4/3、5/1、10/9、10/23、10/30、11/6、12/4。',
    staytime: '2.5-3.5小時',
    modified: '2024-08-22 16:12:40 +08:00',
    url: 'https://www.travel.taipei/zh-tw/attraction/details/19',
    category: [
      {
        id: 13,
        name: '歷史建築',
      },
      {
        id: 15,
        name: '藝文館所',
      },
      {
        id: 19,
        name: '親子共遊',
      },
      {
        id: 25,
        name: '無障礙旅遊推薦景點',
      },
    ],
    target: [
      {
        id: 61,
        name: '親子共學',
      },
      {
        id: 62,
        name: '校外教學',
      },
    ],
    service: [
      {
        id: 141,
        name: '無障礙設施',
      },
      {
        id: 144,
        name: '餐飲',
      },
      {
        id: 145,
        name: '購物',
      },
      {
        id: 146,
        name: '公廁',
      },
      {
        id: 147,
        name: '停車場',
      },
      {
        id: 148,
        name: '失物招領',
      },
      {
        id: 149,
        name: '廣播服務',
      },
      {
        id: 150,
        name: '寄物櫃',
      },
    ],
    friendly: [
      {
        id: 387,
        name: '英語友善',
      },
      {
        id: 388,
        name: '日語友善',
      },
      {
        id: 389,
        name: '韓語友善',
      },
      {
        id: 390,
        name: '行動裝置充電',
      },
      {
        id: 392,
        name: '無障礙友善服務',
      },
      {
        id: 393,
        name: '性別友善',
      },
      {
        id: 394,
        name: '信用卡/悠遊卡/第三方支付服務',
      },
      {
        id: 395,
        name: '素食友善',
      },
      {
        id: 396,
        name: '友善廁所',
      },
      {
        id: 398,
        name: 'WiFi友善',
      },
      {
        id: 400,
        name: '哺(集)乳友善',
      },
      {
        id: 401,
        name: '穆斯林友善',
      },
    ],
    images: [
      {
        src: 'https://www.travel.taipei/image/221733',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/221734',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/221735',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/221736',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/221737',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/221738',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/221739',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/221740',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/221731',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/221732',
        subject: '',
        ext: '.jpg',
      },
    ],
    files: [],
    links: [
      {
        src: 'https://www.npm.gov.tw/Article.aspx?sNo=02007001',
        subject: '門票及開放時間',
      },
    ],
  },
  {
    id: 17,
    name: '七星山系_天母古道親山步道',
    name_zh: null,
    open_status: 1,
    introduction:
      '天母古道親山步道穿越士林華岡地區的西北山坡，也是紗帽山南邊的鞍部，屬於早年魚路古道的後段，涵蓋華岡至天母間的數條步道，沿著大水管構築，潺潺溪水、原始林相，步行其間，讓人倍覺涼爽舒適。步道還可順遊經翠峰瀑布至猴洞產業道路的「翠峰步道」，夾峙在山間林蔭中，走起來特別涼爽舒適。\r\n\r\n天母古道曾經是金山與天母間重要的連絡要道，自從仰德大道開通後，這條早年的便道就成為名符其實的古道，近年更躍昇為熱門的登山路線，每逢假日遊人如織。\r\n\r\n天母古道生態景觀\r\n天母古道全區海拔高度從約300公尺至120公尺屬於臺灣低海拔亞熱帶闊葉林生態系。從大屯山鞍部吹來的東北季風帶來強風、雨水和低溫，使山腰古道迎風面，呈現暖溫帶闊葉林景致；相反的山腰避風面溪谷陰溼地環境則利於熱帶闊葉樹種生長，如熱帶板根、幹生花、纏勒等現象。天母古道雖海拔僅300公尺，卻有著熱帶、亞熱帶及暖溫帶闊葉林等不同生態之壓縮型生態系環境，相當難得而珍貴。\r\n\r\n◎特別提醒山友：步道下切翠峰瀑布的岔路附近，容易看見猴群出沒，當您看見猴群出現時，請不要任意餵食，以免猴兒為爭搶食物，不小心傷害到您喔！\r\n\r\n水管路步道\r\n水管路步道自日據時代便是保安林區的水源重地，不僅林相原始豐富，沿途築水而居的蕨類、姑婆芋等植物，更見茂盛而繁多。水管路係為接引第三水源地泉水到天母、士林一帶所闢建，步道前段爬坡路沿線已不見大水管，而步道後段水管就埋在步道底下。\r\n\r\n1930年間水管上陸續鋪設石板和水泥作為保護，水管路就因此而形成，水管路與步道在天母地區因山勢漸緩才分道揚鑣。目前步道入口處的三角埔發電廠是步道的起點，也是水管路的終點。\r\n\r\n入山林前先暖身\r\n\r\n自登山口出發，得先經過上千級石階的考驗，沿途有人遞熱茶熱湯免費試喝，才剛覺得熱，遮陽帽就出現了，若是口渴，林間還有果汁、茶，和甜美的地瓜湯在等著你。奇怪，還沒到陽明山呢，「在地」的蔬菜、竹筍、地瓜就已一字排開。\r\n\r\n說是有一千多個階梯，就當作是進入山林前的「暖身」。首先映入眼簾是龍眼樹林，石階兩旁高大的龍眼樹，有的樹腰粗到要兩人合抱。從前，龍眼可是這裡的主要產業。再往上走，出現傳說中的黑色大水管，山路也突然變得陡直。\r\n\r\n上坡路不免要費點體力，累了，中途和盡頭都有涼亭可以歇歇腳。站在中途涼亭旁回望，天母市區已在山腳下，小有成就感，即使有點喘吁吁也能繼續向前行；走到盡頭，如果天氣晴朗，還能遠眺林口台地，據說從這裡觀看台北夜景也很不錯喲。\r\n\r\n終於走完這段陡坡，在蓄水池旁洗把臉擦擦汗，馬上就要進入林蔭坦途囉。\r\n\r\n詩意的步道之旅\r\n造訪過水管路步道的人，多半都會愛上這段路。沿途林木蔽日，夏日走在如履平地的山路上倍覺舒適涼爽；冬季只聽見北風在溪谷中呼嘯，但不覺有刺骨寒風。這裡的路面平整，很適合駐足觀景。漫步林間小徑，視野由眺望天母、北投轉換至山林溪谷，山間梯田與裊裊煙霧構成如詩如畫的動人美景。\r\n\r\n海拔僅300公尺高的水管路步道，因為自日據時代便是「水源重地」和「保安林區」，林相原始豐富，不但沿途可見許多築水而居的蕨類、姑婆芋等指標性植物，生活其間的植物更高達三百餘種，可見生態環境受到很好的保護。\r\n\r\n路旁山崖的石壁上時有石頭堆砌，從岩壁流出的山泉水流入圳溝，吸引不少溪蝦和蝌蚪在此聚集。步道後段還有一條小水溝，清澈的水流同樣來自山上湧出的泉水，裡面有許多沼蝦和螃蟹，更是多種蜻蜓及蛙類繁殖的場所。從秋季到次年春季時，不時可以聽到斯文豪氏赤蛙如鳥叫的鳴聲。清晨或黃昏時段，還有機會看到台灣獼猴在此出沒呢。\r\n\r\n水道水　潺潺流\r\n水管路步道源自於日據時期，為了接引第三水源地的泉水到天母、士林一帶所開闢。行走在沿山壁開鑿的山徑，已不見前段爬坡路上的大水管，其實後段水管就埋在步道底下。一九三○年代，水管之上陸續鋪設石板和泥土作為保護，水管路就此成形。接近天母地區，因為山勢漸展，水管與步道才「分道揚鑣」。\r\n\r\n現在靠山崖的路上見到圳溝，石頭堆砌引導山泉流下的水溝彷彿是昔日藉水管引水的縮影；站在上坡路的水管旁，還可聽到大水管內急速的水流聲。\r\n\r\n步道入口的三角埔發電廠是步道的起點，也是水管道的終點，儘管已功成身退，依然見證了這水道的今與昔。\r\n',
    open_time: '',
    zipcode: '111',
    distric: '士林區',
    address: '111 臺北市士林區中山北路7段232巷',
    tel: '+886-2-27593001',
    fax: '',
    email: '',
    months: '01,07,02,08,03,09,04,10,05,11,06,12',
    nlat: 25.12764,
    elong: 121.53367,
    official_site: '',
    facebook: '',
    ticket: '',
    remind:
      '備註事項：\r\n1.路徑長度：登山步道約2.6公里，全線約3.75公里\r\n2.海拔高度：約387公尺\r\n3.步行時間：約2小時',
    staytime: '',
    modified: '2024-08-22 15:31:08 +08:00',
    url: 'https://www.travel.taipei/zh-tw/attraction/details/17',
    category: [
      {
        id: 16,
        name: '戶外踏青',
      },
      {
        id: 19,
        name: '親子共遊',
      },
    ],
    target: [
      {
        id: 61,
        name: '親子共學',
      },
      {
        id: 66,
        name: '健行族',
      },
    ],
    service: [
      {
        id: 146,
        name: '公廁',
      },
    ],
    friendly: [],
    images: [
      {
        src: 'https://www.travel.taipei/image/221111',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/221112',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/221113',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/221114',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/221115',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/221106',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/221107',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/221108',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/221109',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/221110',
        subject: '',
        ext: '.jpg',
      },
    ],
    files: [],
    links: [],
  },
  {
    id: 6,
    name: '社子島環島與二重疏洪道自行車道',
    name_zh: null,
    open_status: 1,
    introduction:
      '社子島位於基隆河與淡水河之交匯處，地質為沙洲型態，該地區處處可見稻田橫亙，菜園綠茵，展現老農村民風純樸的美麗景緻。該地區利用堤頂建設自行車道，吸引許多自行車愛好者前往，社子島沙洲沙尾可以看見基隆河與淡水河交匯波濤澎湃的景象，每當夕陽西下，金黃色落日餘暉揮灑在河面上閃閃動人，遠眺大屯山及觀音山綿延天邊的景緻，教人美不勝收。\r\n\r\n往南還可銜接百齡橋左岸自行車，這裡有許多大型的各式球場，而且經常可以看見國內外著名的球隊在此練球，騎乘之餘欣賞開闊的運動廣場人群，既充實又熱鬧。二重疏洪道環狀自行車道全長24公里，穿越堤頂道路進入公園區域，不同主題的河濱綠地，可以花上很多時間去探險。',
    open_time: '開放空間',
    zipcode: '111',
    distric: '士林區',
    address: '111 臺北市士林區社子島自行車道',
    tel: '+886-2-27258149',
    fax: '',
    email: '',
    months: '01,07,02,08,03,09,04,10,05,11,06,12',
    nlat: 25.10985,
    elong: 121.46606,
    official_site: 'https://heo.gov.taipei/cp.aspx?n=1F4BB3A41B266BB7',
    facebook: '',
    ticket: '',
    remind:
      '1.長度：社子島9公里，二重疏洪道24公里 \r\n2.騎乘時間：社子島約40分鐘、二重疏洪道約100分鐘\r\n\r\n路況屬於平坦路段、騎乘時舒適度普通，沿途可以看見基隆河與淡水河交匯波滔景像及遠眺大屯山、觀音山的景致，但因為路程較遠，較適合體力較好者。',
    staytime: '',
    modified: '2024-08-22 14:31:08 +08:00',
    url: 'https://www.travel.taipei/zh-tw/attraction/details/6',
    category: [
      {
        id: 12,
        name: '單車遊蹤',
      },
      {
        id: 19,
        name: '親子共遊',
      },
    ],
    target: [
      {
        id: 61,
        name: '親子共學',
      },
      {
        id: 63,
        name: '單車族',
      },
    ],
    service: [
      {
        id: 146,
        name: '公廁',
      },
      {
        id: 147,
        name: '停車場',
      },
    ],
    friendly: [],
    images: [
      {
        src: 'https://www.travel.taipei/image/63343',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/63341',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/63342',
        subject: '',
        ext: '.jpg',
      },
    ],
    files: [],
    links: [],
  },
  {
    id: 5,
    name: '關渡_金色水岸_八里左岸自行車道',
    name_zh: null,
    open_status: 1,
    introduction:
      '基隆河匯入淡水河之前，繞著社子島轉出一個美麗的弧彎，在其北岸與磺港溪以西地帶，保留了都會臺北極其珍貴的稻香田園，連結起河口紅樹林自然保護區，讓人得以在很短的距離內隔絕塵囂嘈雜，單車踩踏其間，尤其能夠體會早年農村氛圍的樸素簡單、踏實自在。夕照裡堤道漫步，河風微微、鳥鳴吱吱，關渡自然保護區生機盎然中，獨有浪漫閒適的野趣滿點。\r\n\r\n穿越關渡平原的自行車道，是全線非封閉性的路徑，西側端點為關渡宮，往東沿著關渡防潮堤至八仙福德祠，轉90度往北穿越關渡平原，直到北投中央北路捷運軌道南側，穿出去便是政戰學校西邊的稻香路。 無法自行攜帶單車的遊人，以關渡宮為起點較方便，一則靠近捷運站，再者可於該處租到自行車或雙人協力車。 關渡宮沿河堤段原有的攤販已完全撤離，改成好走的人行步道，跨越中港河小橋旁停泊的漁船也外移至淡水河邊，雖然少了扁舟停泊的漁港懷舊味，水域卻也另有清爽的風貌。',
    open_time: '開放空間',
    zipcode: '112',
    distric: '北投區',
    address: '112 臺北市北投區關渡水岸腳踏車道',
    tel: '+886-2-27258149',
    fax: '',
    email: '',
    months: '01,07,02,08,03,09,04,10,05,11,06,12',
    nlat: 25.11382,
    elong: 121.48003,
    official_site: '',
    facebook: '',
    ticket: '',
    remind:
      '1.長度：11.9公里，其中貴子坑溪自行車道約5公里 \r\n2.騎乘時間：約40分鐘',
    staytime: '',
    modified: '2024-08-22 14:24:05 +08:00',
    url: 'https://www.travel.taipei/zh-tw/attraction/details/5',
    category: [
      {
        id: 12,
        name: '單車遊蹤',
      },
      {
        id: 16,
        name: '戶外踏青',
      },
      {
        id: 17,
        name: '藍色水路',
      },
      {
        id: 19,
        name: '親子共遊',
      },
    ],
    target: [
      {
        id: 61,
        name: '親子共學',
      },
      {
        id: 62,
        name: '校外教學',
      },
      {
        id: 63,
        name: '單車族',
      },
      {
        id: 65,
        name: '賞鳥族',
      },
      {
        id: 66,
        name: '健行族',
      },
    ],
    service: [
      {
        id: 146,
        name: '公廁',
      },
    ],
    friendly: [],
    images: [
      {
        src: 'https://www.travel.taipei/image/63340',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/63335',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/63337',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/63339',
        subject: '',
        ext: '.jpg',
      },
    ],
    files: [],
    links: [],
  },
  {
    id: 4,
    name: '景美溪河濱自行車道',
    name_zh: null,
    open_status: 1,
    introduction:
      '有青山綠水相伴的景美溪河濱自行車道，沿線有動物園，政大球場及青草綠茵，溪流常有魚群穿梭，適合攜家帶眷全家出遊的路線。\r\n\r\n沿線的景觀相當豐富，翠綠草地，清澈溪流讓人感覺非常舒適，此外，於道南河濱公園內還設有各式各樣的運動場所，如籃球場、溜冰場、羽球場等，每到傍晚便可看到許多人或走或騎自行車到這兒來進行各種運動，是一個充滿活力的自行車道。',
    open_time: '開放空間',
    zipcode: '116',
    distric: '文山區',
    address: '116 臺北市文山區景美溪左右岸 道南河濱公園',
    tel: '+886-2-27258149',
    fax: '',
    email: '',
    months: '01,07,02,08,03,09,04,10,05,11,06,12',
    nlat: 24.98135,
    elong: 121.56629,
    official_site: 'https://heo.gov.taipei/cp.aspx?n=A30EAFDA61A1C236',
    facebook: '',
    ticket: '',
    remind:
      '1.長度：左岸3.8公里，右岸8.1公里。\r\n2.騎乘時間：左岸約25分鐘，右岸約15分鐘，可由道南橋連接兩岸。',
    staytime: '',
    modified: '2024-08-22 14:15:25 +08:00',
    url: 'https://www.travel.taipei/zh-tw/attraction/details/4',
    category: [
      {
        id: 12,
        name: '單車遊蹤',
      },
      {
        id: 16,
        name: '戶外踏青',
      },
      {
        id: 19,
        name: '親子共遊',
      },
    ],
    target: [
      {
        id: 61,
        name: '親子共學',
      },
      {
        id: 63,
        name: '單車族',
      },
    ],
    service: [
      {
        id: 146,
        name: '公廁',
      },
    ],
    friendly: [],
    images: [
      {
        src: 'https://www.travel.taipei/image/63334',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/63329',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/63331',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/63333',
        subject: '',
        ext: '.jpg',
      },
    ],
    files: [],
    links: [],
  },
  {
    id: 3,
    name: '大佳碼頭',
    name_zh: null,
    open_status: 1,
    introduction:
      '大佳碼頭位於圓山基隆河左岸，圓山昔稱圓仔山，是大龍峒地形上的龍頭之地，由於基隆河流經，過去曾是海水進出的湖沼地區，經過開挖發掘的圓山遺址及貝塚，證明當時先民生活的位址。緊依著圓山的劍潭之地，因國姓爺鄭成功插劍水潭取水而得名，日據時期日人曾於今圓山飯店旁忠烈祠西側之地，興建臺灣神社及神宮外苑花園，由此可見其地理位置之重要性。\r\n\r\n大佳碼頭位於基隆河南岸、大直橋以西約200公尺的地方。這裡是「藍色水路」的遊艇碼頭，從這裡有大佳到圓山、大佳到內湖科學園區單點來回兩個航線。\r\n\r\n\r\n\r\n',
    open_time: '開放空間',
    zipcode: '104',
    distric: '中山區',
    address: '104 臺北市中山區大佳碼頭',
    tel: '+886-2-27208889',
    fax: '',
    email: '',
    months: '01,07,02,08,03,09,04,10,05,11,06,12',
    nlat: 25.07588,
    elong: 121.53742,
    official_site: '',
    facebook: '',
    ticket: '',
    remind: '',
    staytime: '',
    modified: '2024-08-22 14:07:52 +08:00',
    url: 'https://www.travel.taipei/zh-tw/attraction/details/3',
    category: [
      {
        id: 17,
        name: '藍色水路',
      },
    ],
    target: [
      {
        id: 62,
        name: '校外教學',
      },
    ],
    service: [
      {
        id: 146,
        name: '公廁',
      },
    ],
    friendly: [],
    images: [
      {
        src: 'https://www.travel.taipei/image/63327',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/63328',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/63324',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/63325',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/63326',
        subject: '',
        ext: '.jpg',
      },
    ],
    files: [],
    links: [],
  },
  {
    id: 2,
    name: '關渡碼頭',
    name_zh: null,
    open_status: 1,
    introduction:
      '關渡原名甘豆門，因背倚觀音山和大屯山，面向淡水河，成為一處地勢險要的港口，早年先民由關渡碼頭進入移居臺灣北部開墾，因此關渡的開發甚早，後因兩河(基隆河、淡水河)河口泥沙淤積，水運才逐漸沒落。\r\n\r\n關渡碼頭位於關渡自然公園及關渡宮旁，每當假日或夜晚均可見遊客駐足關渡碼頭週邊散步休息，亦有許多單車族由八里經關渡大橋前來，或由淡水前來，沿途風光明媚，是一處極佳的賞景地點。\r\n\r\n\r\n\r\n\r\n\r\n\r\n',
    open_time: '開放空間',
    zipcode: '112',
    distric: '北投區',
    address: '112 臺北市北投區關渡碼頭',
    tel: '+886-2-27208889',
    fax: '',
    email: '',
    months: '01,07,02,08,03,09,04,10,05,11,06,12',
    nlat: 25.120870809229285,
    elong: 121.4619791507721,
    official_site: '',
    facebook: '',
    ticket: '',
    remind: '',
    staytime: '',
    modified: '2024-08-22 14:04:13 +08:00',
    url: 'https://www.travel.taipei/zh-tw/attraction/details/2',
    category: [
      {
        id: 17,
        name: '藍色水路',
      },
    ],
    target: [
      {
        id: 62,
        name: '校外教學',
      },
    ],
    service: [
      {
        id: 146,
        name: '公廁',
      },
    ],
    friendly: [],
    images: [
      {
        src: 'https://www.travel.taipei/image/63313',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/63315',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/63318',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/63319',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/63320',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/63322',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/63323',
        subject: '',
        ext: '.jpg',
      },
    ],
    files: [],
    links: [],
  },
  {
    id: 2642,
    name: '｢花現台北杜鵑花季｣ 溫羅汀咖啡街區巷弄',
    name_zh: null,
    open_status: 1,
    introduction:
      '春風微拂、陽光和煦的3月份，正是台北杜鵑花盛開的時刻，沿著台北杜鵑花的賞花地圖，來到溫羅汀街區巷弄漫步，在這一帶安靜的街道中，每條巷弄都隱身著具有質感、文青、復古、清新、溫馨、文藝氣息等各式各樣的書店、咖啡廳、文創小店。但你/妳有沒有發現有些不一樣呢？每年台北杜鵑花季，在地店家開始紛紛妝點上繽紛的杜鵑花窗貼，當人們一走進巷弄中，彷彿置身於粉紅杜鵑花海中，浪漫的杜鵑花語訴說著「我們的約定」，今年也一起相約來參與台北杜鵑花季吧！快準備好你的相機，跟著杜鵑花散步在粉色浪漫的咖啡巷弄，一起拍一波網美照吧！咖啡香、書香、浪漫杜鵑花，等著與你一起共度美好、幸福、有愛的台北杜鵑花季~',
    open_time: '',
    zipcode: '106',
    distric: '大安區',
    address: '106 臺北市大安區溫州街、羅斯福路、汀州路',
    tel: '+886-2-27208889',
    fax: '',
    email: '',
    months: '03',
    nlat: 25.022605,
    elong: 121.5332326,
    official_site: '',
    facebook: '',
    ticket: '',
    remind: '',
    staytime: '',
    modified: '2024-08-21 14:33:14 +08:00',
    url: 'https://www.travel.taipei/zh-tw/attraction/details/2642',
    category: [
      {
        id: 24,
        name: '主題商街',
      },
    ],
    target: [],
    service: [],
    friendly: [],
    images: [],
    files: [],
    links: [],
  },
  {
    id: 2649,
    name: '捷運綠廊',
    name_zh: null,
    open_status: 1,
    introduction:
      '台北捷運綠廊係貫穿台北車站至淡水站沿線的生活圈，乘載了居民及旅客的共同記憶，也記載著台北城市發展的軌跡。不論是心中山線形公園、心雙連線形公園、圓山線形公園或是台北捷運線形公園等，都導入都市空間縫合概念，搭配周邊整體環境，進行該段線形公園設施優化及區域特色亮點營造，提供居民一個舒適、嶄新的休閒空間。',
    open_time: '開放空間',
    zipcode: '104',
    distric: '中山區',
    address: '104 臺北市中山區穿台北車站至淡水站沿線生活圈',
    tel: '+886-2-21812345',
    fax: '',
    email: '',
    months: '01,07,02,08,03,09,04,10,05,11,06,12',
    nlat: 25.069271083169735,
    elong: 121.51975862681866,
    official_site: '',
    facebook: '',
    ticket: '',
    remind: '',
    staytime: '',
    modified: '2024-08-21 11:58:58 +08:00',
    url: 'https://www.travel.taipei/zh-tw/attraction/details/2649',
    category: [
      {
        id: 499,
        name: '其他',
      },
    ],
    target: [],
    service: [],
    friendly: [],
    images: [
      {
        src: 'https://www.travel.taipei/image/373688',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/373689',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/373690',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/373687',
        subject: '',
        ext: '.jpg',
      },
    ],
    files: [],
    links: [],
  },
  {
    id: 2647,
    name: '經國七海文化園區',
    name_zh: null,
    open_status: 1,
    introduction:
      '「經國七海文化園區」總面積3.98公頃，建築基地約兩千坪，園區周邊保留大面積植栽綠地、公共藝術與親水步道，建築設計與自然環境相調和，以符合鑽石級綠建築為目標。\r\n▲圖片來源：經國七海文化園區\r\n\r\n園區以七海寓所古蹟及蔣經國總統圖書館為核心，附設遊客中心，結合七海潭與劍潭山的美景，以及環湖步道，構成整體文化園區。我們以緬懷經國先生，活化古蹟，延續歷史生命力為原則來規劃營運此重要故居，希望成為臺北市文化深度旅遊之新景點，以及具有豐富歷史意涵的人文新地標。\r\n▲圖片來源：經國七海文化園區\r\n\r\n七海寓所\r\n七海寓所為經國先生夫婦的生活空間，内部陳設簡單，體現經國先生樸實無華與親和平易的風範。七海寓所另設有遊客停等區，此空間展示寓所大事記、文物、寓所環景導覽、寓所建築與生態介紹等。\r\n▲圖片來源：經國七海文化園區\r\n\r\n陳列廳\r\n第一陳列廳以「臺灣現代化的推手」為主題，介紹經國先生生平事蹟及家庭生活，呈現經國先生的人格特質、重要政績與人生歷練。第二陳列廳以「歲月沉思錄」為主題，帶領遊客回到經國先生的年代，透過經國先生的日記、侍從及僚屬眼中的經國先生、經國先生的書畫作品等，讓遊客認識不同面向的經國先生。\r\n▲圖片來源：經國七海文化園區',
    open_time: '',
    zipcode: '104',
    distric: '中山區',
    address: '104 臺北市中山區北安路301號',
    tel: '+886-2-25326077',
    fax: '',
    email: 'service@ccklibrary.org.tw',
    months: '01,07,02,08,03,09,04,10,05,11,06,12',
    nlat: 25.078730111095105,
    elong: 121.5368952602148,
    official_site: 'https://ccklibrary.org.tw/',
    facebook: '',
    ticket: '參觀收費標準及入園資訊請以官方網站公告為主',
    remind:
      '1.嚴禁煙火、飲食、喧嘩、奔跑、攜帶寵物（導盲犬除外）或危險物品等；請配合服務人員的導引，並維持園區內的秩序及整潔。\r\n2.請愛護園區內展示文物，如有損及展覽品或相關設施者，須負賠償責任。\r\n3.園區內有提供地下停車場（停車費用：平日$30 /小時、假日$50 /小時）',
    staytime: '',
    modified: '2024-08-21 11:52:45 +08:00',
    url: 'https://www.travel.taipei/zh-tw/attraction/details/2647',
    category: [
      {
        id: 13,
        name: '歷史建築',
      },
      {
        id: 15,
        name: '藝文館所',
      },
    ],
    target: [],
    service: [
      {
        id: 141,
        name: '無障礙設施',
      },
      {
        id: 144,
        name: '餐飲',
      },
      {
        id: 145,
        name: '購物',
      },
      {
        id: 146,
        name: '公廁',
      },
      {
        id: 147,
        name: '停車場',
      },
      {
        id: 150,
        name: '寄物櫃',
      },
    ],
    friendly: [],
    images: [],
    files: [],
    links: [],
  },
  {
    id: 2651,
    name: '師大龍泉商圈',
    name_zh: null,
    open_status: 1,
    introduction:
      '因位於師範大學旁而得名，主要道路為師大路及龍泉街，因往內延伸的巷道多，狹長型道路形成徒步區，以學區為中心帶動商圈美食、平價服飾店及特色咖啡店大量聚集，以供應南北各地學生及來台學習華語之外籍人士的日常生活需求。',
    open_time: '請依各店家營業時間為主',
    zipcode: '106',
    distric: '大安區',
    address: '106 臺北市大安區師大龍泉商圈',
    tel: '+886-930-099-833',
    fax: '',
    email: 'brassjoy2016@gmail.com',
    months: '01,07,02,08,03,09,04,10,05,11,06,12',
    nlat: 25.024506695365563,
    elong: 121.52933794443847,
    official_site: '',
    facebook:
      'https://www.facebook.com/%E5%B8%AB%E5%A4%A7%E9%BE%8D%E6%B3%89%E5%95%86%E5%9C%88-%E5%B8%AB%E5%A4%A7%E5%A4%9C%E5%B8%82-103968169634554/?paipv=0&eav=AfZpYSvM912FowJoYoM33iHid-PNlXe1QcF6ep1aiN0m3UIE9gY85AKJYLflaXaW_uA&_rdr',
    ticket: '',
    remind: '',
    staytime: '',
    modified: '2024-08-21 11:34:04 +08:00',
    url: 'https://www.travel.taipei/zh-tw/attraction/details/2651',
    category: [
      {
        id: 23,
        name: '夜市商圈',
      },
    ],
    target: [],
    service: [],
    friendly: [],
    images: [
      {
        src: 'https://www.travel.taipei/image/373682',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/373679',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/373680',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/373681',
        subject: '',
        ext: '.jpg',
      },
    ],
    files: [],
    links: [],
  },
  {
    id: 2653,
    name: '文化大學',
    name_zh: null,
    open_status: 1,
    introduction:
      '中國文化大學共有五個校區，總面積115公頃。校本部位於陽明山華岡，毗連國家公園，景象優美、空氣清新、交通便利，校內建築以中國宮殿式建築呈現，外型典雅巍峨。',
    open_time: '全天開放',
    zipcode: '111',
    distric: '士林區',
    address: '111 臺北市士林區華岡路55號',
    tel: '+886-2-28610511',
    fax: '',
    email: '',
    months: '01,07,02,08,03,09,04,10,05,11,06,12',
    nlat: 25.13654340858378,
    elong: 121.53925895690918,
    official_site: 'https://www.pccu.edu.tw/',
    facebook: 'https://www.facebook.com/PCCUOfficial',
    ticket: '',
    remind: '',
    staytime: '',
    modified: '2024-08-21 11:14:28 +08:00',
    url: 'https://www.travel.taipei/zh-tw/attraction/details/2653',
    category: [
      {
        id: 16,
        name: '戶外踏青',
      },
      {
        id: 19,
        name: '親子共遊',
      },
    ],
    target: [],
    service: [],
    friendly: [],
    images: [
      {
        src: 'https://www.travel.taipei/image/373672',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/373673',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/373671',
        subject: '',
        ext: '.jpg',
      },
    ],
    files: [],
    links: [],
  },
  {
    id: 2656,
    name: '大屯瀑布',
    name_zh: null,
    open_status: 1,
    introduction:
      '陽明山大屯瀑布係位於陽明山公園附近，鮮少人探訪的一處秘境，由多個瀑布組成，沿途步道會經過長滿青苔的長廊，步道的盡頭是可以一望台北盆地無盡景色的景觀台。',
    open_time: '',
    zipcode: '112',
    distric: '北投區',
    address: '112 臺北市北投區大屯瀑布',
    tel: '+886-2-27593001',
    fax: '',
    email: '',
    months: '01,07,02,08,03,09,04,10,05,11,06,12',
    nlat: 25.16183290541385,
    elong: 121.53686106204987,
    official_site: '',
    facebook: '',
    ticket: '',
    remind: '',
    staytime: '',
    modified: '2024-08-20 14:16:29 +08:00',
    url: 'https://www.travel.taipei/zh-tw/attraction/details/2656',
    category: [
      {
        id: 16,
        name: '戶外踏青',
      },
      {
        id: 19,
        name: '親子共遊',
      },
    ],
    target: [],
    service: [],
    friendly: [],
    images: [
      {
        src: 'https://www.travel.taipei/image/373660',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/373661',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/373662',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/373663',
        subject: '',
        ext: '.jpg',
      },
    ],
    files: [],
    links: [],
  },
  {
    id: 2657,
    name: '水車寮步道',
    name_zh: null,
    open_status: 1,
    introduction:
      '水車寮步道鄰近竹子湖地區，是著名的賞花及賞螢步道。每到繡球花季和海芋季盛開之時，滿是絡繹不絕的賞花人潮。春末夏初螢火蟲出沒之際，夜晚還可來場賞螢生態之旅。',
    open_time: '',
    zipcode: '112',
    distric: '北投區',
    address: '112 臺北市北投區竹子湖路29-1號',
    tel: '+886-2-27593001',
    fax: '',
    email: '',
    months: '01,07,02,08,03,09,04,10,05,11,06,12',
    nlat: 25.17126171019935,
    elong: 121.53925895690918,
    official_site: 'https://gisweb.taipei.gov.tw/release/?p=6-2-4',
    facebook: '',
    ticket: '',
    remind: '',
    staytime: '',
    modified: '2024-08-20 14:08:24 +08:00',
    url: 'https://www.travel.taipei/zh-tw/attraction/details/2657',
    category: [
      {
        id: 16,
        name: '戶外踏青',
      },
      {
        id: 19,
        name: '親子共遊',
      },
    ],
    target: [],
    service: [],
    friendly: [],
    images: [
      {
        src: 'https://www.travel.taipei/image/373657',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/373658',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/373659',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/373656',
        subject: '',
        ext: '.jpg',
      },
    ],
    files: [],
    links: [],
  },
  {
    id: 2658,
    name: '中華科技大學',
    name_zh: null,
    open_status: 1,
    introduction:
      '中華科技大學，校本部位於台北市南港區，比鄰中央研究院，環境鬧中取靜。另外有分部位於新竹縣橫山鄉及雲林縣古坑鄉。',
    open_time: '全天開放',
    zipcode: '115',
    distric: '南港區',
    address: '115 臺北市南港區研究院路三段245號',
    tel: '+886-2-2782-1862',
    fax: '',
    email: '',
    months: '01,07,02,08,03,09,04,10,05,11,06,12',
    nlat: 25.0336221955809,
    elong: 121.60989761352539,
    official_site: 'https://www.cust.edu.tw/www/index.htm',
    facebook: 'https://www.facebook.com/cust.edu.tw?locale=zh_TW',
    ticket: '',
    remind: '',
    staytime: '',
    modified: '2024-08-20 14:02:10 +08:00',
    url: 'https://www.travel.taipei/zh-tw/attraction/details/2658',
    category: [
      {
        id: 16,
        name: '戶外踏青',
      },
    ],
    target: [],
    service: [],
    friendly: [],
    images: [
      {
        src: 'https://www.travel.taipei/image/373654',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/373655',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/373653',
        subject: '',
        ext: '.jpg',
      },
    ],
    files: [],
    links: [],
  },
  {
    id: 244,
    name: '優人神鼓山上劇場',
    name_zh: null,
    open_status: 1,
    introduction:
      '優人神鼓-山上劇場座落在貓空的老泉山上，2007年登錄為文化景觀，不僅是劇團的家園、創作與工作場域，更是靈感的來源與生命的根基。在此可以找到純粹與豐富的自然與生命交流經驗。',
    open_time: '週一至週五 09:00 ~ 18:00',
    zipcode: '116',
    distric: '文山區',
    address: '116 臺北市文山區木新路二段156-1號',
    tel: '+886-2-29100528',
    fax: '+886-2-29100727',
    email: 'service@utheatre.org',
    months: '01,07,02,08,03,09,04,10,05,11,06,12',
    nlat: 24.96581,
    elong: 121.57379,
    official_site: 'http://www.utheatre.org.tw/',
    facebook: 'https://www.facebook.com/utheatre1988',
    ticket: '',
    remind: '優人神鼓山上劇場 地址：台北市文山區老泉街26巷30號',
    staytime: '',
    modified: '2024-08-19 17:40:43 +08:00',
    url: 'https://www.travel.taipei/zh-tw/attraction/details/244',
    category: [
      {
        id: 15,
        name: '藝文館所',
      },
      {
        id: 18,
        name: '公共藝術',
      },
    ],
    target: [
      {
        id: 61,
        name: '親子共學',
      },
      {
        id: 62,
        name: '校外教學',
      },
      {
        id: 66,
        name: '健行族',
      },
    ],
    service: [
      {
        id: 146,
        name: '公廁',
      },
    ],
    friendly: [],
    images: [],
    files: [],
    links: [],
  },
  {
    id: 2659,
    name: '綠光平台',
    name_zh: null,
    open_status: 1,
    introduction:
      '民眾可搭乘貓空纜車至指南宮站，出站即可到「綠光平台」眺望貓空山區美景。平台係利用太陽能板儲存電力發光，入夜後燈光絢麗，不僅是纜車乘客觀賞景點，也是環保綠能教育空間。',
    open_time: '',
    zipcode: '116',
    distric: '文山區',
    address: '116 臺北市文山區指南路三段157巷200號',
    tel: '+886-2-27593001',
    fax: '',
    email: '',
    months: '01,07,02,08,03,09,04,10,05,11,06,12',
    nlat: 24.978735080898257,
    elong: 121.58990442752838,
    official_site: '',
    facebook: '',
    ticket: '',
    remind: '',
    staytime: '',
    modified: '2024-08-19 17:37:10 +08:00',
    url: 'https://www.travel.taipei/zh-tw/attraction/details/2659',
    category: [
      {
        id: 16,
        name: '戶外踏青',
      },
      {
        id: 19,
        name: '親子共遊',
      },
    ],
    target: [],
    service: [],
    friendly: [],
    images: [
      {
        src: 'https://www.travel.taipei/image/373649',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/373650',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/373651',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/373652',
        subject: '',
        ext: '.jpg',
      },
    ],
    files: [],
    links: [],
  },
  {
    id: 2660,
    name: '12生肖步道',
    name_zh: null,
    open_status: 1,
    introduction:
      '十二生肖步道位在貓纜指南宮站旁邊，由底下的迎仙亭出發，步道沿著山坡而建，最高處可以看到指南宮月下老人，為「指南風景區」內規劃的「情人聖地」，又稱「情人步道」。',
    open_time: '開放空間',
    zipcode: '116',
    distric: '文山區',
    address: '116 臺北市文山區12生肖步道',
    tel: '+886-2-27593001',
    fax: '',
    email: '',
    months: '01,07,02,08,03,09,04,10,05,11,06,12',
    nlat: 24.97894707842671,
    elong: 121.58995796678856,
    official_site: '',
    facebook: '',
    ticket: '',
    remind: '',
    staytime: '',
    modified: '2024-08-19 17:33:26 +08:00',
    url: 'https://www.travel.taipei/zh-tw/attraction/details/2660',
    category: [
      {
        id: 16,
        name: '戶外踏青',
      },
      {
        id: 19,
        name: '親子共遊',
      },
    ],
    target: [],
    service: [],
    friendly: [],
    images: [
      {
        src: 'https://www.travel.taipei/image/373648',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/373645',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/373646',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/373647',
        subject: '',
        ext: '.jpg',
      },
    ],
    files: [],
    links: [],
  },
  {
    id: 2661,
    name: '戀人平台',
    name_zh: null,
    open_status: 1,
    introduction:
      '指南宮月下老人旁的木棧平台設置有筊杯月娘椅，被稱為「戀人平台」。',
    open_time: '',
    zipcode: '116',
    distric: '文山區',
    address: '116 臺北市文山區指南路三段157巷200號',
    tel: '+886-2-27593001',
    fax: '',
    email: '',
    months: '01,07,02,08,03,09,04,10,05,11,06,12',
    nlat: 24.978831821695877,
    elong: 121.58966638245644,
    official_site: '',
    facebook: '',
    ticket: '',
    remind: '',
    staytime: '',
    modified: '2024-08-19 17:25:08 +08:00',
    url: 'https://www.travel.taipei/zh-tw/attraction/details/2661',
    category: [
      {
        id: 16,
        name: '戶外踏青',
      },
      {
        id: 19,
        name: '親子共遊',
      },
    ],
    target: [],
    service: [],
    friendly: [],
    images: [
      {
        src: 'https://www.travel.taipei/image/373641',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/373642',
        subject: '',
        ext: '.jpg',
      },
      {
        src: 'https://www.travel.taipei/image/373643',
        subject: '',
        ext: '.jpg',
      },
    ],
    files: [],
    links: [],
  },
];
